### ISSUE TITLE
Modurality, split in two seperate libraries.

### ISSUE THREAD

**Issue by aloiscochard** [ReactiveMongo/Play-ReactiveMongo#111] opened 2015-01-14 15:24 UTC
It's kind of a shame that the handlers are mixed with the play plugin.

I don't care about play, I just want the bson <-> json stuff... could you think about modularizing things in that regard?

Cheers

**Comment by cchantep** [comment] 2015-03-13 09:10
(Duplicate of #103)

**Closed** 2015-06-26 18:46 UTC
